/*
 * Generated by Bluespec Compiler, version 2019.05.beta2 (build a88bf40, 2019-05-24)
 * 
 * On Sat May  7 11:12:41 CST 2022
 * 
 */

/* Generation options: keep-fires */
#ifndef __model_mkTests_h__
#define __model_mkTests_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"

#include "bs_model.h"
#include "mkTests.h"

/* Class declaration for a model of mkTests */
class MODEL_mkTests : public Model {
 
 /* Top-level module instance */
 private:
  MOD_mkTests *mkTests_instance;
 
 /* Handle to the simulation kernel */
 private:
  tSimStateHdl sim_hdl;
 
 /* Constructor */
 public:
  MODEL_mkTests();
 
 /* Functions required by the kernel */
 public:
  void create_model(tSimStateHdl simHdl, bool master);
  void destroy_model();
  void reset_model(bool asserted);
  void get_version(unsigned int *year,
		   unsigned int *month,
		   char const **annotation,
		   char const **build);
  time_t get_creation_time();
  void * get_instance();
  void dump_state();
  void dump_VCD_defs();
  void dump_VCD(tVCDDumpType dt);
  tUInt64 skip_license_check();
};

/* Function for creating a new model */
extern "C" {
  void * new_MODEL_mkTests();
}

#endif /* ifndef __model_mkTests_h__ */
